games/urls.py
from django.urls import path
from . import views

app_name = 'games'


urlpatterns = [
    path('', views.index, name='index'),
    path('game/<int:game_id>/', views.game_detail, name='game_detail'),
    path('cart/', views.cart, name='cart'),
    path('cart/delete/<int:game_id>/', views.delete_from_cart, name='delete_from_cart'),
    path('cart/add/<int:game_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/make_order/', views.make_order, name='make_order'),
    path('cart/<int:order_id>/order_success/', views.order_success, name='order_success'),
    path('cart/checkout/', views.checkout, name='checkout'),
    path('profile/<str:username>/', views.public_profile, name='public_profile'),
]

gameshop/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('games.urls', namespace='games')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import (LogoutView,
                                       PasswordChangeView,
                                       LoginView,
                                       PasswordResetView,
                                       PasswordChangeDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)

from . import views


app_name = 'users'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/',
         LoginView.as_view(
             template_name='users/login.html'),
         name='login'),
    path('signup/',
         views.SighUp.as_view(), name='signup'),
    path('logout/',
         LogoutView.as_view(
             template_name='users/logged_out.html'),
         name='logout'),
    path('password_change/',
         PasswordChangeView.as_view(
             template_name='users/password_change_form.html'),
         name='password_change_form'),
    path('password_reset/',
         PasswordResetView.as_view(
             template_name='users/password_reset_form.html'),
         name='password_reset_form'),
    path('password_reset/done/',
         PasswordChangeDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='passwrod_reset_complete'),
]

templates/includes/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:comment_create' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text |addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

<div class="row">
  {% for comment in comments %}
    <div class="media mb-4">
      <div class="media-body">
        <h5 class="mt-0">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.username }}
          </a>
        </h5>
          <p>
          {{ comment.text }}
          </p>
          <p>
          <button type="submit" class="btn btn-primary">
            <a class="nav-link link-light" href="{% url 'posts:delete_comment' comment.pk %}">Удалить комментарий</a>
          </button>
          </p>
        </div>
      </div>
  {% endfor %}
</div>

templates/includes/footer.html
<footer class="bg-dark text-light py-4 mt-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h5>StarShop</h5>
                <p>Лучший магазин компьютерных игр</p>
            </div>
            <div class="col-md-6 text-end">
                <p>&copy; 2025 StarShop. Все права защищены.</p>
            </div>
        </div>
    </div>
</footer>

templates/includes/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'games:index' %}">GameShop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}">
                            <i class="fas fa-user me-1"></i>Профиль
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'games:cart' %}">
                            <i class="fas fa-shopping-cart me-1"></i>Корзина 
                            <span class="badge bg-primary">{{ user.cart.items.count }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/includes/header_first.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'games:index' %}">GameShop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'games:index' %}">Главная</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile' %}">
                            <i class="fas fa-user me-1"></i>Профиль
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>